### ISSUE TITLE
Need Markdown Editor

### ISSUE THREAD

**Issue by tyeeman** [boiteasite/cmsuno#3]
Very nice work here! ckEditor is ok, but I need markdown editor, can a plugin be created for this. I'm not sure if the current markdown plugin replaces ckeditor or not??

**Comment by boiteasite** [comment]
Hi
What kind of editor do you need :
 - Markdown => HTML (for a page creation),
 - Plain text + button => Markdown (for a readme),
 - Other ?

**Comment by tyeeman** [comment]
Greetings
   Yes, I need Markdown => HTML for page creation, that would be great! Can it be done easily?

**Comment by boiteasite** [comment]
OK, I will update the Markdown plugin for that : a textarea for your content and a name for the shortcode to paste in your page.

**Comment by tyeeman** [comment]
ok, thanks a lot! I'll be waiting.

**Comment by boiteasite** [comment]
Hi,

Done. Version 1.3.

Regards

2017-01-08 20:40 GMT+01:00 tyeeman <notifications@github.com>:

**Comment by tyeeman** [comment]
Thanks a lot, much appreciated!

Small error on your markdown date of revision - says 2016 instead of 2017. 

I will give it a try.

**Comment by tyeeman** [comment]
Sorry for the long delay, just trying to get the markdown plugin to work. I have copied the markdown plugin folder into the "plugins" folder of cmsuno and I have "enabled" the plugin on the plugin page but I still get ckeditor when I go to create a page. Do I have to do something different than the above to get a plugin to work?

Update - I removed the version numbers of the plugin folder names and now for all plugins the settings show up fine.

Some small bugs - 

Re: Markdown plugin - I pasted your readme.md into the "MD Content" box and it does show properly in the page but in the plugin page the content spills over out of the square content box like shown below.

![mdspillover](https://user-images.githubusercontent.com/4469306/28078626-5be90fce-661a-11e7-89ec-d49e0af026a7.png)

External link in Multipage Menu Manager is not formatted correctly. Adds html at end of url. Dots and slashes do not appear. Clicking delete X for external link does nothing also.

Multimenu pages, other than home page show outside the top menu bar.

**Comment by boiteasite** [comment]
Hi,

> but in the plugin page the content spills over out of the square content box like shown below

Thanks for your report. I will fix that soon.

Copy for Multipage plugin. I will check that.

Regards

**Comment by boiteasite** [comment]
Hi,

New update for both plugin.

> Clicking delete X for external link does nothing also

You need save the changes.

Regards
